### ISSUE TITLE
Zero division easter egg

### ISSUE THREAD

**Issue by not-nef** [Futura-Py/FluxCalc#20]
This is just a little idea i had: We could add a small easter egg: the application will not say error after a few times of trying, but things like: "Stop dividing by zero!", "Seriously, stop", "STOP IT!!!!!!". And things like that. I thought this will be a cool little secret.

**Comment by not-nef** [comment]
I can implement this tomorrow if you approve it @HuyHung1408

**Comment by HuyHung1408** [comment]
That's very cool, you can implement it

**Comment by im-coder-lg** [comment]
Also - I made one now, we could try this - if a user(probably a 6-year old) does division by zero(we know math, it leads us to those two spiralling loops mathematicians call "infinity", ain't it?), we could show warnings and end with "Fluent Python Calculator will shut down if there is one more division by zero. It leads you nowhere!".

Creativity at its finest.

The name is too long, can we try finding a shorter one?

**Comment by im-coder-lg** [comment]
Also(another also ,oops another one) - welcome to the team @HuyHung1408!

**Comment by not-nef** [comment]
Yeah, wee definitely need to change the name. And btw @HuyHung1408 i am having issues with compiling. win32mica doesnt seem to work when the program is compiled.

**Comment by sumeshir26** [comment]
Did you include Ntkutils?

**Comment by not-nef** [comment]
Yes, and btw ntkutils had a bug with mica that i fixed yesterday. Will push to pypi and github tomorrow.

**Comment by HuyHung1408** [comment]
> Also(another also, oops another one) - welcome to the team @HuyHung1408!

Hi y'all XDD

**Comment by HuyHung1408** [comment]
> Yeah, wee definitely need to change the name. And btw @HuyHung1408 i am having issues with compiling. win32mica doesnt seem to work when the program is compiled.

I faced that issue too

**Comment by HuyHung1408** [comment]
Added it in! What do you guys think?
https://user-images.githubusercontent.com/86362423/178089981-c8e17324-818e-4c6f-84ba-a0f4a7e95299.mp4

**Comment by HuyHung1408** [comment]
Added this in, what do you guys think?

https://user-images.githubusercontent.com/86362423/178092447-711c81e7-019e-4b9d-a336-9b010c2ae9e1.mp4

**Comment by not-nef** [comment]
cool!

**Comment by sumeshir26** [comment]
Nice!

**Comment by HuyHung1408** [comment]
Thanks y'all

**Comment by HuyHung1408** [comment]
Believe it or not @not-nef's txt2 inspired me to continue coding 🤯

**Comment by not-nef** [comment]
Yooo that makes me veeery happy! 😊

**Comment by im-coder-lg** [comment]
Add the rickroll!!! It's gonna be so sick! My new rickroll weapon to use on bullies is ready. Imagine the frustration when someone does that, not knowing the fact that division happens when both values have some real relation. Real, not rational, meaning irrational too. But Zero, it is not really common, so it leads to infinity. Since it is Not Defined, we declare it as that.

I might as well teach math at school lol

**Comment by HuyHung1408** [comment]
added rickroll when they choose no when fluxcalc ask them to stop or you want to open like directly

> Add the rickroll!!! It's gonna be so sick! My new rickroll weapon to use on bullies is ready. Imagine the frustration when someone does that, not knowing the fact that division happens when both values have some real relation. Real, not rational, meaning irrational too. But Zero, it is not really common, so it leads to infinity. Since it is Not Defined, we declare it as that.
> 
> I might as well teach math at school lol
