### ISSUE TITLE
Multiplication Improvement

### ISSUE THREAD

**Issue by not-nef** [Futura-Py/FluxCalc#22]
This Calculation is mathematically correct:

`3(5-2)`

But FPC would only accept this:

`3x(5-2)`

**Comment by im-coder-lg** [comment]
Wait, if we apply BODMAS/PEMDAS calculation power here, it could work, right? I mean, look at this(for the one who hasn't heard of our BODMAS rule, also adding PEMDAS for helpfulness):

| Letters | Full-Form |
| -------- | ----------- |
| B / P | Brackets / Parentheses |
| O / E | Order / Exponents |
| D / M | Division / Multiplication(left -> right) |
| M / D | Multiplication / Division(from left to right) |
| A (both) | Addition |
| S (both) | Subtraction|

So, according to the rule, it should follow the parentheses, then go for multiplication. By "follow the parentheses", I mean that it must complete the expression inside it, be it a vinculum, closed, open or curly bracket, it should follow a _strict_ order.

**Comment by not-nef** [comment]
im out

**Comment by im-coder-lg** [comment]
bro wut happen

**Comment by im-coder-lg** [comment]
Got a(rather stupidly awesome) idea. We'll make our own calculator Python API that uses BODMAS and PEMDAS for calculating. Anyone in?

**Comment by sumeshir26** [comment]
Hmmm.... These days I bareley have enough time since my new grade has me soo busy

**Comment by sumeshir26** [comment]
Rather than making our own apil why dont we just use pythons `eval('equation')` to do that?

**Comment by not-nef** [comment]
Good question

**Comment by im-coder-lg** [comment]
> Hmmm.... These days I bareley have enough time since my new grade has me soo busy

Yeah same. It's like this - wake up, do morning routine, go to schools return back, eat lunch, do homework. Touching the laptop seems to be impossible.

**Comment by im-coder-lg** [comment]
> Rather than making our own apil why dont we just use pythons `eval('equation')` to do that?

Well, we can proofread, right?
