### ISSUE TITLE
Decide a new name

### ISSUE THREAD

**Issue by not-nef** [Futura-Py/FluxCalc#32]

**Comment by im-coder-lg** [comment]
I think you just need to head to a random name generator. CalcX doesn't seem good, but PyCalc does seem nice.

**Comment by rdbende** [comment]
PyCalc: https://github.com/jacobhallberg/PyCalc

**Comment by HuyHung1408** [comment]
> PyCalc: https://github.com/jacobhallberg/PyCalc

Yeah

**Comment by not-nef** [comment]
So is FluxCalc ok? @HuyHung1408

**Comment by HuyHung1408** [comment]
> So is FluxCalc ok? @HuyHung1408 

yup

**Comment by im-coder-lg** [comment]
I meant FluXCalc, notice the capital X, since it seems to fit in with our other app, TimerX. Only thing is the X is in fourth place.

**Comment by not-nef** [comment]
Hmmmmmm, ok, will change later
