### ISSUE TITLE
Move calculations to a different .py file

### ISSUE THREAD

**Issue by not-nef** [Futura-Py/FluxCalc#35]
What do you think about that @HuyHung1408 ? I would like to move the calculation part of the program to a different .py file, as it is about to get larger. Only an idea tho, i just want to make the code look good. No problem if you dont want it.

**Comment by not-nef** [comment]
I just want to get approval so i can finally start "really" working on this amazing program!

**Comment by im-coder-lg** [comment]
My opinion: good idea since we need to add BODMAS or PEMDAS functions. That might make the project better. Heck, we could also publish it on PyPI if it gets so huge!

**Comment by not-nef** [comment]
Just waitin for @HuyHung1408 's approval

**Comment by HuyHung1408** [comment]
yup, great idea. Sorry for not being online much at this time, my final exams is coming so I have much things to do. Hope that I'll be free when I finished the school

**Comment by not-nef** [comment]
no problem!
