### ISSUE TITLE
Buttons need to click multiple times before they can be insert into the content

### ISSUE THREAD

**Issue by HuyHung1408** [Futura-Py/FluxCalc#40]
More info: Only happens in light mode because the 'pressed' state in light mode is a bit transparent, but the windows was also transparent for the mica effects so it needs to click multiple times before they can be insert into the content. This does not happen in dark mode, because the 'pressed' state in dark mode is not transparent. This was not happens before switching to the sv_ttk because I modified the 'pressed' state. Not sure if you guys facing the same issue, if yes, I will ask [rdbende](https://github.com/rdbende) to modify the button to not transparent 

https://user-images.githubusercontent.com/86362423/164738773-eeb3e5c1-9327-49ff-83a6-482e21669943.mp4

**Comment by HuyHung1408** [comment]
If this issue can be fixed, I will release the v1.1, this is largest issue yet need to be fixed as soon as possible!

**Comment by not-nef** [comment]
There is only one thing left before the release of 2.0 so i think we can wait for 2.0 when we fix this bug

**Comment by im-coder-lg** [comment]
I feel like I have seen this bug before... Can't tell where, not with my PC(vacations, not with any PCs here unfortunately :/), but I think there was a good enough fix for it.

**Comment by HuyHung1408** [comment]
I will be back to work in about 2 more weeks, final exams are coming, good luck on exams y'all!

**Comment by im-coder-lg** [comment]
Good luck! Mine was done last month btw, but anyway, study well and get that A.

**Comment by not-nef** [comment]
@HuyHung1408 Any progress on this?

**Comment by HuyHung1408** [comment]
> @HuyHung1408 Any progress on this?

[This is what rdbende said](https://github.com/rdbende/Sun-Valley-ttk-theme/issues/26#issuecomment-1107395085). But im-coder-lg knows what to do so I'm waiting for him

**Comment by HuyHung1408** [comment]
> Say whaaaa? I said that I have seen this before, not that I was the person to give a fix! I think this happened in TimerX, since that's the other place where we got blur in.

Sorry lol

**Comment by not-nef** [comment]
I didnt even look if this happens on my side, will check after school today

**Comment by HuyHung1408** [comment]
Sooo, I have a fixed for it 👍. This won't happen when it release to user, but still will still happens when you run it from VS code or other code editor!

**Comment by HuyHung1408** [comment]
What is going to be the next version of FluxCalc? Version 1.1 right? I'm done with exams but also currently on a vacation with my family so there is no computer. New version possibly in the weekend of next week!

**Comment by not-nef** [comment]
Next Version is 2.0! You can also look at the milestone tab for more info

**Comment by HuyHung1408** [comment]
ah i see, thanks

**Comment by im-coder-lg** [comment]
Y'all do as you wish, but keep it semantic. It helps, y'know.

**Comment by not-nef** [comment]
@HuyHung1408 Sooooooooo... have you found a fix?

**Comment by HuyHung1408** [comment]
> @HuyHung1408 Sooooooooo... have you found a fix?

I edit the button image after convert it to exe using PyInstaller so it won't be an issue, still happens when you run it through VS cods tho

**Comment by HuyHung1408** [comment]
FluxCalc setup is in the draft in the release. You guys can check if the bug still exists

**Comment by not-nef** [comment]
I didnt test it yet, but assuming it works, can you tell me how you fixed it, so i can maybe include it in the script so we dont have to do it manually everytime?

**Comment by HuyHung1408** [comment]
> I didnt test it yet, but assuming it works, can you tell me how you fixed it, so i can maybe include it in the script so we dont have to do it manually everytime?

I copy the 'hover' state and replace the 'pressed' state with it, that's all

**Comment by not-nef** [comment]
Did that even fix it

**Comment by HuyHung1408** [comment]
I rolled back to Windows 10 so I can't test that lol, but properly will work

**Comment by HuyHung1408** [comment]
Upgraded to Windows 11 a few hours ago, problem solved and everything works. Published a new release, thanks for all y'all help
